version: '3.4'

services:
  stomp-producer:
    image: se-stomp-producer
    build:
      context: Stomp
      dockerfile: producer/Dockerfile

  matrix-info-aggregator:
    image: se-mta
    build:
      context: MatrixInfoAggregator
      dockerfile: ./Dockerfile
